import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Header } from 'components/Header'
import { Main } from 'components/main/Main'
import { Footer } from 'components/Footer'


const inter = Inter({ subsets: ['latin'] })

const Home = () => {
  return (
    <>
      <Head>
        <title>ECサイト</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@200;300;400;500;600;700&display=swap" rel="stylesheet"></link>
      </Head>
      <Header />
      <Main></Main>
      <Footer />
    </>
  )
}
export default Home